# Generated by Django 4.1.5 on 2023-12-10 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ElevatorModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("elevator_number", models.IntegerField()),
                ("curr_floor", models.IntegerField(default=1)),
                ("door_open", models.BooleanField(default=True)),
                ("working", models.BooleanField(default=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[(1, "UP"), (-1, "DOWN"), (0, "STANDING STILL")],
                        default=0,
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ElevatorSystemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("total_elevators", models.IntegerField(default=1)),
                ("total_floors", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="ElevatorRequestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_floor", models.IntegerField()),
                ("destination_floor", models.IntegerField()),
                (
                    "elevator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elevator.elevatormodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="elevatormodel",
            name="elevator_system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="elevator.elevatorsystemmodel",
            ),
        ),
    ]
